### ISSUE TITLE
add R

### ISSUE THREAD

**Issue by floswald** [tlamadon/dev-container-julia#1]
https://rocker-project.org/images/devcontainer/features.html

**Comment by tlamadon** [comment]
For basic support of R, it is a matter of simply changing the base image in the Docker file. I chose to use the one with Julia only to try to stay lean. Substituting the first two lines will fix that:

```
#FROM docker.io/jupyter/datascience-notebook:latest
FROM docker.io/jupyter/julia-notebook
```

The reason I did this is also because this is specially targeted at julia projects. The dev container here will pull info from the Project file to build and cache the dependencies.

To do the same with R we need to add code to get project descriptions, etc... we probably need to do that separately. I don't even know what is good package manager for R these days.

What do you think?

**Comment by floswald** [comment]
ok sounds good. I'm looking around for R. there are some frightening options (*install all packages using the MRAN repo by DATE*). i guess something like `renv` would be best, but i don't know how that lines up next to the alternatives. 

stupid question: there is no way to build an image which would *contain* all required packages already so that you don't even need a package manager? 

[here's](https://github.com/analythium/covidapp-shiny/blob/main/05-docker-renv/Dockerfile?ref=hosting.analythium.io) an example using `renv` to build an image

**Comment by tlamadon** [comment]
it is basically part of the container. the packages are just added as the
last layer. Since it is the only thing that should be changing I think it
is a good place to do it.

the dev container can (as the julia one does) simply run a docker file so
anything is possible. We could also call a user R script that installs a
list a of packages. Seems easy enough.

**Comment by tlamadon** [comment]
We put a tentative dev container for R in the renv brench:
https://github.com/tlamadon/dev-container-julia/tree/renv

I think that successfully closes this issue.
